
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author Like
 */
public class Interfaz extends javax.swing.JFrame {
    private final int [][] terminal=new int[4][4];
    private final int [][] inicial=new int[4][4];
    Puzzle obj;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() 
    {
        initComponents();
        b1.setText("1");   b2.setText("2");   b3.setText("3");   b4.setText("4");
        b5.setText("5");   b6.setText("6");   b7.setText("7");   b8.setText("8");
        b9.setText("9");   b10.setText("10"); b11.setText("11");  b12.setText("12");
        b13.setText("13"); b14.setText("14"); b15.setText("15"); b16.setText("0");        
        
        inicial[0][0] = 1;  inicial[0][1] = 2; inicial[0][2] = 3; inicial[0][3] = 4;
        inicial[1][0] = 5;  inicial[1][1] = 6; inicial[1][2] = 7; inicial[1][3] = 8;
        inicial[2][0] = 9;  inicial[2][1] = 10; inicial[2][2] =11; inicial[2][3] =12;
        inicial[3][0] = 13;  inicial[3][1] =14; inicial[3][2] =15; inicial[3][3] = 0;
        
        bb1.setText("1");bb2.setText("2");bb3.setText("3");bb4.setText("4");
        bb5.setText("5");bb6.setText("6");bb7.setText("7");bb8.setText("8");
        bb9.setText("9");bb10.setText("10");bb11.setText("0");bb12.setText("11");
        bb13.setText("13");bb14.setText("14");bb15.setText("15");bb16.setText("12");
        terminal[0][0] = 1;   terminal[0][1] = 2;    terminal[0][2] = 3;   terminal[0][3] = 4;
        terminal[1][0] = 5;   terminal[1][1] = 6;    terminal[1][2] = 7;   terminal[1][3] = 8;
        terminal[2][0] = 9;   terminal[2][1] = 10;   terminal[2][2] = 0;  terminal[2][3] = 11;
        terminal[3][0] = 13;  terminal[3][1] = 14;   terminal[3][2] = 15;  terminal[3][3] = 12;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        b1 = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b8 = new javax.swing.JToggleButton();
        b7 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b10 = new javax.swing.JToggleButton();
        b13 = new javax.swing.JToggleButton();
        b9 = new javax.swing.JToggleButton();
        b14 = new javax.swing.JToggleButton();
        b11 = new javax.swing.JToggleButton();
        b15 = new javax.swing.JToggleButton();
        b12 = new javax.swing.JToggleButton();
        b16 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        bb1 = new javax.swing.JToggleButton();
        bb2 = new javax.swing.JToggleButton();
        bb3 = new javax.swing.JToggleButton();
        bb4 = new javax.swing.JToggleButton();
        bb8 = new javax.swing.JToggleButton();
        bb7 = new javax.swing.JToggleButton();
        bb6 = new javax.swing.JToggleButton();
        bb5 = new javax.swing.JToggleButton();
        bb10 = new javax.swing.JToggleButton();
        bb13 = new javax.swing.JToggleButton();
        bb9 = new javax.swing.JToggleButton();
        bb14 = new javax.swing.JToggleButton();
        bb11 = new javax.swing.JToggleButton();
        bb15 = new javax.swing.JToggleButton();
        bb12 = new javax.swing.JToggleButton();
        bb16 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 102));

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));

        b1.setText("1");
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b13.setText("13");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b11.setText("0");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b15.setText("15");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b12.setText("11");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b16.setText("12");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 5));

        bb1.setText("1");
        bb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb1ActionPerformed(evt);
            }
        });

        bb2.setText("2");
        bb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb2ActionPerformed(evt);
            }
        });

        bb3.setText("3");
        bb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb3ActionPerformed(evt);
            }
        });

        bb4.setText("4");
        bb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb4ActionPerformed(evt);
            }
        });

        bb8.setText("8");
        bb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb8ActionPerformed(evt);
            }
        });

        bb7.setText("7");
        bb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb7ActionPerformed(evt);
            }
        });

        bb6.setText("6");
        bb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb6ActionPerformed(evt);
            }
        });

        bb5.setText("5");
        bb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb5ActionPerformed(evt);
            }
        });

        bb10.setText("10");
        bb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb10ActionPerformed(evt);
            }
        });

        bb13.setText("13");
        bb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb13ActionPerformed(evt);
            }
        });

        bb9.setText("9");
        bb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb9ActionPerformed(evt);
            }
        });

        bb14.setText("14");
        bb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb14ActionPerformed(evt);
            }
        });

        bb11.setText("11");
        bb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb11ActionPerformed(evt);
            }
        });

        bb15.setText("15");
        bb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb15ActionPerformed(evt);
            }
        });

        bb12.setText("12");
        bb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb12ActionPerformed(evt);
            }
        });

        bb16.setText("0");
        bb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bb1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bb5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bb2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bb6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bb10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(bb13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bb14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bb15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bb16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bb2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bb6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(bb1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bb5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(bb10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(bb9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bb12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bb11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bb13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bb14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bb15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bb16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("INICIAL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TERMINAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(153, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("                             PUZZLE");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 255, 102), new java.awt.Color(153, 255, 102), new java.awt.Color(153, 255, 102), new java.awt.Color(153, 255, 102)));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            if(!verificar(terminal))
                JOptionPane.showMessageDialog(null,"Número repetido en Terminal");
            else
            {
                if(!verificar(inicial))
                JOptionPane.showMessageDialog(null,"Número repetido en Inicial");
                else
                {
                    obj=new Puzzle(inicial,terminal); 
                    texto.setText(obj.imprime());               
            }   }
            
            
    }//GEN-LAST:event_jButton1ActionPerformed
 private boolean verificar(int[][] tablero) 
    {
    System.out.println ("verificando");
    LinkedList<Integer> verificados= new LinkedList<Integer>();
    for (int [] a: tablero)
    {
        for(int b:a)
        {
        if(verificados.contains(b)) 
        { 
            return false;
        }
        verificados.add(b);
        }
    } 
    return true;
    }
    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
    String x= leerinicial(1);
    b1.setText(x); 
    }//GEN-LAST:event_b1MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
     String x= leerinicial(2);
    b2.setText(x);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
     String x= leerinicial(3);
    b3.setText(x);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
     String x= leerinicial(4);
    b4.setText(x);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
    String x= leerinicial(5);
    b5.setText(x);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
     String x= leerinicial(6);
    b6.setText(x);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
 String x= leerinicial(7);
    b7.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
 String x= leerinicial(8);
    b8.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
 String x= leerinicial(9);
    b9.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
 String x= leerinicial(10);
    b10.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
    String x= leerinicial(11);
    b11.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
    String x= leerinicial(12);
    b12.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
 String x= leerinicial(13);
    b13.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
 String x= leerinicial(14);
    b14.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
 String x= leerinicial(15);
    b15.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
    String x= leerinicial(16);
    b16.setText(x);        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void bb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb1ActionPerformed
    String x= leerTerminal(1);
    bb1.setText(x);
    }//GEN-LAST:event_bb1ActionPerformed

    private void bb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb2ActionPerformed
    String x= leerTerminal(2);
    bb2.setText(x);  // TODO add your handling code here:
    }//GEN-LAST:event_bb2ActionPerformed

    private void bb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb3ActionPerformed
    String x= leerTerminal(3);
    bb3.setText(x);
    }//GEN-LAST:event_bb3ActionPerformed

    private void bb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb4ActionPerformed
     String x= leerTerminal(4);
    bb4.setText(x);   // TODO add your handling code here:
    }//GEN-LAST:event_bb4ActionPerformed

    private void bb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb5ActionPerformed
      String x= leerTerminal(5);
    bb5.setText(x);  // TODO add your handling code here:
    }//GEN-LAST:event_bb5ActionPerformed

    private void bb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb6ActionPerformed
     String x= leerTerminal(6);
    bb6.setText(x);   // TODO add your handling code here:
    }//GEN-LAST:event_bb6ActionPerformed

    private void bb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb7ActionPerformed
     String x= leerTerminal(7);
    bb7.setText(x);   // TODO add your handling code here:
    }//GEN-LAST:event_bb7ActionPerformed

    private void bb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb8ActionPerformed
     String x= leerTerminal(8);
    bb8.setText(x);   // TODO add your handling code here:
    }//GEN-LAST:event_bb8ActionPerformed

    private void bb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb9ActionPerformed
    String x= leerTerminal(9);
    bb9.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb9ActionPerformed

    private void bb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb10ActionPerformed
    String x= leerTerminal(10);
    bb10.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb10ActionPerformed

    private void bb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb11ActionPerformed
    String x= leerTerminal(11);
    bb11.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb11ActionPerformed

    private void bb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb12ActionPerformed
    String x= leerTerminal(12);
    bb12.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb12ActionPerformed

    private void bb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb13ActionPerformed
    String x= leerTerminal(13);
    bb13.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb13ActionPerformed

    private void bb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb14ActionPerformed
    String x= leerTerminal(14);
    bb14.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb14ActionPerformed

    private void bb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb15ActionPerformed
    String x= leerTerminal(15);
    bb15.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb15ActionPerformed

    private void bb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb16ActionPerformed
    String x= leerTerminal(16);
    bb16.setText(x);    // TODO add your handling code here:
    }//GEN-LAST:event_bb16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b10;
    private javax.swing.JToggleButton b11;
    private javax.swing.JToggleButton b12;
    private javax.swing.JToggleButton b13;
    private javax.swing.JToggleButton b14;
    private javax.swing.JToggleButton b15;
    private javax.swing.JToggleButton b16;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton b3;
    private javax.swing.JToggleButton b4;
    private javax.swing.JToggleButton b5;
    private javax.swing.JToggleButton b6;
    private javax.swing.JToggleButton b7;
    private javax.swing.JToggleButton b8;
    private javax.swing.JToggleButton b9;
    private javax.swing.JToggleButton bb1;
    private javax.swing.JToggleButton bb10;
    private javax.swing.JToggleButton bb11;
    private javax.swing.JToggleButton bb12;
    private javax.swing.JToggleButton bb13;
    private javax.swing.JToggleButton bb14;
    private javax.swing.JToggleButton bb15;
    private javax.swing.JToggleButton bb16;
    private javax.swing.JToggleButton bb2;
    private javax.swing.JToggleButton bb3;
    private javax.swing.JToggleButton bb4;
    private javax.swing.JToggleButton bb5;
    private javax.swing.JToggleButton bb6;
    private javax.swing.JToggleButton bb7;
    private javax.swing.JToggleButton bb8;
    private javax.swing.JToggleButton bb9;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables


    private String leerinicial(int indice) 
    {
        String x=null;
        switch(indice)
        {
            case 1:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[0][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 2: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[0][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 3:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[0][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 4: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[0][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 5: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[1][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 6: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[1][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 7: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[1][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 8: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[1][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 9: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[2][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 10: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[2][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 11: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[2][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 12: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
               try{
                inicial[2][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 13: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[3][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 14: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[3][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 15:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[3][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 16:  
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                inicial[3][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
        }
        return x;
    }
    private String leerTerminal(int indice) 
    {
        String x=null;
        switch(indice)
        {
            case 1:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[0][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 2: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[0][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 3:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[0][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 4: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[0][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 5: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[1][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 6: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[1][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 7: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[1][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 8: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[1][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 9: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[2][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 10: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[2][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 11: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[2][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 12: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
               try{
                terminal[2][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 13: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[3][0] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 14: 
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[3][1] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 15:   
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[3][2] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
            case 16:  
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                try{
                terminal[3][3] = Integer.parseInt(x);
                }catch (Exception e)
                {
                x=JOptionPane.showInputDialog (null,"Numero? ","0-16",JOptionPane.PLAIN_MESSAGE).trim();
                }
                break;
        }
        return x;
    }
}
